### ISSUE TITLE
Cytoscape gets stuck when HAM is started!

### ISSUE THREAD

**Issue by smd-faizan** [smd-faizan/CySpanningTree#2]
must be bcoz we used thread.join() function. Try using Cytoscape task!

**Comment by srikanthBezawada** [comment]
I also faced the issue.. I guess so, let's post in the forum ?

**Comment by smd-faizan** [comment]
Resolved: https://github.com/smd-faizan/CySpanningTree/commit/043c75e7e5daa0c9a405cd7ecd7d2103b039bc83
